services:
  webstack:
    build:
      context: ../../
      dockerfile: docker/webstack/Dockerfile  
    image: skyzgh/webstack-go:latest
    container_name: webstack
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
       - ./data/upload:/app/upload
       - ./data/db:/app/db
    environment:
      - GIN_MODE=release
    networks:
      - webstack_net

networks:
  webstack_net:
    driver: bridge