services:
  webstack:
    build:
      context: ../../
      dockerfile: docker/webstack/Dockerfile  
    image: webstack:latest
    container_name: webstack
    restart: unless-stopped
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
       - ./data/upload:/app/upload
    env_file:
      - .env
    networks:
      - webstack_net

networks:
  webstack_net:
    driver: bridge